### ISSUE TITLE
500 error in GET /v1/customer/{uid}

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#129]
Edit: Looks like maybe [some profiling annotations](https://github.com/mozilla/subhub/commit/fa8031817fef92ade8a2961fdc11c7c5abac0db9) are causing trouble?

Trying to make a GET request to `/v1/customer/{uid}` and I'm getting a 500 error in our deployed FxA dev instance. I can reproduce locally and get this exception stack trace:

```python
172.17.0.1 - - [15/Jul/2019 22:29:17] "GET /v1/customer/c4279736650649d6801bf291a2a40341 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/app/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/app/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/venv/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/app/venv/lib/python3.7/site-packages/connexion/decorators/security.py", line 299, in wrapper
    return function(request)
  File "/app/venv/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/app/venv/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/app/venv/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "/app/subhub/tracing.py", line 81, in timer
    return function(*args, **kwargs)
TypeError: customer_update() got an unexpected keyword argument 'user'
```

**Comment by lmorchard** [comment]
Looks like I can "fix" the error by commenting out the `@timed` decorator on `customer_update()` - not the *real* fix, but maybe a clue?

```diff
➜  subhub git:(docker-dev) ✗ git diff
diff --git a/subhub/api/payments.py b/subhub/api/payments.py
index e2353d6..849c38f 100644
--- a/subhub/api/payments.py
+++ b/subhub/api/payments.py
@@ -280,7 +280,7 @@ def update_payment_method(uid, data) -> FlaskResponse:
         return {"message": "Customer mismatch."}, 400


-@timed
+# @timed
 def customer_update(uid) -> tuple:
     """
     Provide latest data for a given user
➜  subhub git:(docker-dev) ✗
```

**Comment by bowlofstew** [comment]
Looking now.

**Comment by bowlofstew** [comment]
Pull request targeting the remove of annotations while I go thru reproduction steps: https://github.com/mozilla/subhub/pull/130

**Comment by bowlofstew** [comment]
@lmorchard unrelated question as well.  It looks like from your above report that you are running this in docker via `(docker-dev)` in the text.  Would there be any value in us maintaining a docker image for your purposes (provided the backlog prioritization, etc)?

**Comment by lmorchard** [comment]
> Would there be any value in us maintaining a docker image for your purposes (provided the backlog prioritization, etc)?

Yeah, there'd be a great deal of value in this. 👍 [We have an issue over on FxA to include a docker image of subhub in our local development stacks](https://github.com/mozilla/fxa/issues/1082), where I've been kind of ad-hoc maintaining a Dockerfile. It's tricky because it requires a Stripe key for the local developer, but would be nice to have as an option to enable.

**Comment by bowlofstew** [comment]
Thanks @lmorchard, I will put this into our backlog with the product and agile folks here.  Also as a side note, the PR to fix the reported issue just went back to master :)
