### ISSUE TITLE
Exception thrown when card declined on attemping initial subscription for new customer

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#69]
Starting to do some work around handling & displaying errors and ran into this:

When attempting to create the first subscription for a new customer, and the payment source results in a card declined error (e.g. [using testing CC 4000 0000 0000 9979](https://stripe.com/docs/testing#cards-responses)), the API responds with a 500 Server Error containing an exception stack trace.

Looks like [when a customer is initially created](https://github.com/mozilla/subhub/blob/master/subhub/customer.py#L36), a card error is not expected?

```
127.0.0.1 - - [22/May/2019 17:11:11] "POST /v1/customer/2fbc85f877ca4364a5871136d557167d/subscriptions HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/connexion/decorators/security.py", line 300, in wrapper
    return function(request)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/connexion/decorators/validation.py", line 172, in wrapper
    response = function(request)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "/home/lmorc/devel-local/subhub/subhub/api/payments.py", line 33, in subscribe_to_plan
    origin_system=data["orig_system"],
  File "/home/lmorc/devel-local/subhub/subhub/customer.py", line 69, in existing_or_new_customer
    subhub_accouunt, user_id, email, source_token, origin_system
  File "/home/lmorc/devel-local/subhub/subhub/customer.py", line 40, in create_customer
    metadata={"userid": user_id},
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/stripe/api_resources/abstract/createable_api_resource.py", line 22, in create
    response, api_key = requestor.request("post", url, params, headers)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/stripe/api_requestor.py", line 121, in request
    resp = self.interpret_response(rbody, rcode, rheaders)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/stripe/api_requestor.py", line 372, in interpret_response
    self.handle_error_response(rbody, rcode, resp.data, rheaders)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/stripe/api_requestor.py", line 151, in handle_error_response
    raise err
stripe.error.CardError: Request req_kN6nw8Sf9PsASl: Your card was declined.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1974, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1982, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1974, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict.
```

**Comment by marty331** [comment]
@lmorchard We have an issue/Jira open to return Stripe error messages already.
https://jira.mozilla.com/browse/SS-226

**Comment by lmorchard** [comment]
Maybe this is covered in that jira issue, but FWIW this isn't just about returning an error - this is throwing a "dict is not callable" exception and responding with a full stack trace

**Comment by jackiemunroe** [comment]
@lmorchard the "dict is not callable" was resolved as a part of the Stripe error messages ask. The handler wasn't properly formatting the data before returning the response.
