### ISSUE TITLE
Exception thrown when fetching customer data after deleting last subscription

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#95]
If all subscriptions are cancelled, [payment sources are removed](https://github.com/mozilla/subhub/commit/4c4233bc1664ecb60949c600a7badf2cb947a74d).

The customer record still exists, though - so, when fetching the customer data, it looks like [an exception is thrown related to payment sources here](https://github.com/mozilla/subhub/blob/master/subhub/api/payments.py#L262).

```
127.0.0.1 - - [09/Jun/2019 21:28:44] "GET /v1/customer/93e870bff49b43acb34923bfc840fb55 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/connexion/decorators/security.py", line 300, in wrapper
    return function(request)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/home/lmorc/devel-local/subhub/subhub/.venv/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "/home/lmorc/devel-local/subhub/subhub/api/payments.py", line 246, in customer_update
    return_data = create_update_data(customer)
  File "/home/lmorc/devel-local/subhub/subhub/api/payments.py", line 262, in create_update_data
    return_data["payment_type"] = customer["sources"]["data"][0]["funding"]
IndexError: list index out of range
```

**Comment by marty331** [comment]
Resolved with https://jira.mozilla.com/browse/COPS-575
